include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 18080:80
      - 4443:443
      - 5678:5678
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../tika-server-standard-2.6.0.jar:/tmp/tika-server.jar
      - ../tika-server-standard-2.6.0.jar.md5:/tmp/tika-server.jar.md5
    environment:
      - TZ=${TIMEZONE}
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
